#!/usr/bin/env ruby

# The ultimate awesome Nodejs packaging tool like a supernova!

require_relative 'dependencies.rb'
include Dependencies

workspace = Dir.pwd
name = ARGV[0]

# generate dependency map, downloadable filelist, and complete license string
#Dependencies.write(name)

# generate source.txt

i = 0

if File.exists?(name + '.lst')
    open('source.txt','w:UTF-8') do |f|
	open(name + '.lst','r:UTF-8') do |f1|
		f1.each_line do |l|
			arr = l.strip.split(";")
			url = "http://registry.npmjs.org/" + arr[0] + "/-/" + arr[1] + ".tgz"
			f.write "Source" + i.to_s + ":\s\s" + url + "\n"
			i += 1
		end
	end
    end
end

# download sources
if File.exists?(name + '.lst')
    open(name + '.lst','r:UTF-8') do |f|
		f.each_line do |l|
			arr = l.strip.split(";")
			url = "http://registry.npmjs.org/" + arr[0] + "/-/" + arr[1] + ".tgz"
			IO.popen("wget --tries=0 #{url}")
		end
    end
end
