#!/usr/bin/env ruby

# The ultimate awesome Nodejs packaging tool like a supernova!

require 'fileutils'
require_relative 'dependencies.rb'
include Dependencies

name = ARGV[0]

# generate dependency map, downloadable filelist, and complete license string
Dependencies.write(name)

# generate source.txt

# start from 1, 0 will the be 'phantomjs.json'
i = 1
#=begin
if File.exists?(name + '.lst')
    open(name + '.source','w:UTF-8') do |f|
	open(name + '.lst','r:UTF-8') do |f1|
		f1.each_line do |l|
			arr = l.strip.split(";")
			url = "http://registry.npmjs.org/" + arr[0] + "/-/" + arr[1] + ".tgz"
			f.write "Source" + i.to_s + ":\t" + url + "\n"
			i += 1
		end
	end
    end
end

# delta download sources
if File.exists?(name + '.lst')
    old,new = [],[]
    Dir.glob("./**/*.tgz") do |f|
	old << f.gsub("./","").gsub(".tgz","")
    end

    open(name + '.lst','r:UTF-8') do |f|
	f.each_line do |l|
		new << l.strip!
	end
    end

    cross = old & new
    deltaold = old - cross
    deltanew = new - cross

    deltanew.each do |d|
	url = "http://registry.npmjs.org/" + d.gsub(/-[0-9].*$/,'') + "/-/" + d + ".tgz"
	IO.popen("wget --tries=0 #{url}")
    end
    FileUtils.rm_rf name + '.lst'

    deltaold.each do |d|
	IO.popen("osc delete #{d}.tgz")
    end

end
#=end
